//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.31 at 08:02:00 AM CEST 
//


package com.yourmediashelf.fedora.client.response.objectProfile;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.yourmediashelf.fedora.client.response.objectProfile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ObjDissIndexViewURL_QNAME = new QName("http://www.fedora.info/definitions/1/0/access/", "objDissIndexViewURL");
    private final static QName _ObjLastModDate_QNAME = new QName("http://www.fedora.info/definitions/1/0/access/", "objLastModDate");
    private final static QName _ObjCreateDate_QNAME = new QName("http://www.fedora.info/definitions/1/0/access/", "objCreateDate");
    private final static QName _ObjItemIndexViewURL_QNAME = new QName("http://www.fedora.info/definitions/1/0/access/", "objItemIndexViewURL");
    private final static QName _ObjLabel_QNAME = new QName("http://www.fedora.info/definitions/1/0/access/", "objLabel");
    private final static QName _ObjOwnerId_QNAME = new QName("http://www.fedora.info/definitions/1/0/access/", "objOwnerId");
    private final static QName _ObjState_QNAME = new QName("http://www.fedora.info/definitions/1/0/access/", "objState");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.yourmediashelf.fedora.client.response.objectProfile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObjectProfile }
     * 
     */
    public ObjectProfile createObjectProfile() {
        return new ObjectProfile();
    }

    /**
     * Create an instance of {@link ObjModels }
     * 
     */
    public ObjModels createObjModels() {
        return new ObjModels();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fedora.info/definitions/1/0/access/", name = "objDissIndexViewURL")
    public JAXBElement<String> createObjDissIndexViewURL(String value) {
        return new JAXBElement<String>(_ObjDissIndexViewURL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fedora.info/definitions/1/0/access/", name = "objLastModDate")
    public JAXBElement<XMLGregorianCalendar> createObjLastModDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ObjLastModDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fedora.info/definitions/1/0/access/", name = "objCreateDate")
    public JAXBElement<XMLGregorianCalendar> createObjCreateDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ObjCreateDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fedora.info/definitions/1/0/access/", name = "objItemIndexViewURL")
    public JAXBElement<String> createObjItemIndexViewURL(String value) {
        return new JAXBElement<String>(_ObjItemIndexViewURL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fedora.info/definitions/1/0/access/", name = "objLabel")
    public JAXBElement<String> createObjLabel(String value) {
        return new JAXBElement<String>(_ObjLabel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fedora.info/definitions/1/0/access/", name = "objOwnerId")
    public JAXBElement<String> createObjOwnerId(String value) {
        return new JAXBElement<String>(_ObjOwnerId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fedora.info/definitions/1/0/access/", name = "objState")
    public JAXBElement<String> createObjState(String value) {
        return new JAXBElement<String>(_ObjState_QNAME, String.class, null, value);
    }

}
