//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.31 at 08:02:00 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.fedora.info/definitions/1/0/access/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.yourmediashelf.fedora.client.response.objectProfile;
